name: Build and Push Docker Image

on:
  push:
    branches:
      - 5-feat-dockerize

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/be-62teknologi-test:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push Docker image to Docker Hub
        run: docker push ${DOCKER_USERNAME}/be-62teknologi-test:${{ github.ref_name }}
